[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
rat = { path = "../../" }

futures = "0.3"
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"

serde = { version = "1", features = ["derive"] }
ron = "0.7"
