[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
rat = { path = "../../" }
futures = "0.3"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
ron = "0.7"
async-trait = "0.1"
